In [44]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

# Mean absolute Error

In [2]:
np.mean(np.abs(y_true - y_predicted))

0.5

# Log Loss or Binary cross Entropy

In [3]:
np.log([0])

C:\Users\biya\AppData\Local\Temp/ipykernel_12260/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [26]:
epsilon = 1e-15

In [45]:
y_predicted

array([1, 1, 0, 0, 1])

In [55]:
y_predictednew = [max(i,epsilon) for i in y_predicted]
y_predictednew

[1, 1, 1e-15, 1e-15, 1]

In [56]:
y_predictednew = [min(i, 1-epsilon) for i in y_predictednew]
y_predictednew

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [57]:
y_predictednew = np.array(y_predictednew)
np.log(y_predictednew)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [58]:
-np.mean(y_true*np.log(y_predictednew)+(1-y_true)*np.log(1-y_predictednew))

17.2696280766844

In [59]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predictednew = [max(i,epsilon) for i in y_predicted]
    y_predictednew = [min(i, 1-epsilon) for i in y_predictednew]
    y_predictednew = np.array(y_predictednew)
    return -np.mean(y_true*np.log(y_predictednew)+(1-y_true)*np.log(1-y_predictednew))

In [60]:
log_loss(y_true, y_predicted)

17.2696280766844

# Mean squared Error

In [43]:
np.mean(np.square(y_true - y_predicted))

0.366